#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication fluent3DMeshToFoam tankX.msh # change it to tankY.msh for the other case
runApplication renumberMesh -overwrite

cp -r 0org 0 

runApplication setFields
runApplication transformPoints "translate(0 0 0.4)"
runApplication decomposePar
runParallel foamRun
runApplication reconstructPar

#------------------------------------------------------------------------------
